- name: add ssh key for sabo
  tags: always
  authorized_key:
    user: sabo
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKldYezfyN9QUK3MNs6RJwUh8rS0fwqzgxiFXK1f5JKt ansible"


- name: generate sshd_config file from template
  tags: ssh
  template:
    src: "{{ ssh_template_file }}"
    dest: /etc/ssh/sshd_config
    group: root
    mode: 0644
  notify: restart_sshd
